"""baseline

Revision ID: 93ffbe56c9bc
Revises: 
Create Date: 2026-07-12 23:24:27.886147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93ffbe56c9bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachments', 'extracted_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('email_records_gmail_message_id_key'), 'email_records', type_='unique')
    op.drop_index(op.f('idx_email_records_msg_id'), table_name='email_records')
    op.create_index(op.f('ix_email_records_gmail_message_id'), 'email_records', ['gmail_message_id'], unique=True)
    op.drop_index(op.f('idx_gmail_connections_account'), table_name='gmail_connections')
    op.create_index(op.f('ix_gmail_connections_gmail_account'), 'gmail_connections', ['gmail_account'], unique=False)
    op.alter_column('invoices', 'line_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('idx_invoices_vendor_name'), table_name='invoices')
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_invoices_vendor_name'), 'invoices', ['vendor_name'], unique=False)
    op.drop_index(op.f('idx_ledger_master_code'), table_name='ledger_master')
    op.drop_constraint(op.f('ledger_master_ledger_code_key'), 'ledger_master', type_='unique')
    op.create_index(op.f('ix_ledger_master_ledger_code'), 'ledger_master', ['ledger_code'], unique=True)
    op.drop_index(op.f('idx_organizations_domain'), table_name='organizations')
    op.create_index(op.f('ix_organizations_domain'), 'organizations', ['domain'], unique=False)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_organizations_domain'), table_name='organizations')
    op.create_index(op.f('idx_organizations_domain'), 'organizations', ['domain'], unique=False)
    op.drop_index(op.f('ix_ledger_master_ledger_code'), table_name='ledger_master')
    op.create_unique_constraint(op.f('ledger_master_ledger_code_key'), 'ledger_master', ['ledger_code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_ledger_master_code'), 'ledger_master', ['ledger_code'], unique=False)
    op.drop_index(op.f('ix_invoices_vendor_name'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.create_index(op.f('idx_invoices_vendor_name'), 'invoices', ['vendor_name'], unique=False)
    op.create_index(op.f('idx_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.alter_column('invoices', 'line_items',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_gmail_connections_gmail_account'), table_name='gmail_connections')
    op.create_index(op.f('idx_gmail_connections_account'), 'gmail_connections', ['gmail_account'], unique=False)
    op.drop_index(op.f('ix_email_records_gmail_message_id'), table_name='email_records')
    op.create_index(op.f('idx_email_records_msg_id'), 'email_records', ['gmail_message_id'], unique=False)
    op.create_unique_constraint(op.f('email_records_gmail_message_id_key'), 'email_records', ['gmail_message_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('attachments', 'extracted_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
